Decorate class
hopeforkoami/OOP_school_library pull request #2
Opened 2023-02-08 15:54 UTC by hopeforkoami

In this branch , I:
 ### Interface
 - Create a class `Nameable.`
    * Implement a method called `correct_name` that will raise a `NotImplementedError`.
### Turn your Person class to Nameable
  - Make sure that your Person class inherits from Nameable
  - Make sure that this class has a method `correct_name` implemented. It should simply return the name attribute.
### Prepare base Decorator
 -  Make sure that it inherits from Nameable.
 -  In the constructor assign a nameable object from params to an instance variable.
 -  Implement the `correct_name` method that returns the result of the correct_name method of the `@nameable.`
### Prepare CapitalizeDecorator and TrimmerDecorator
  - For the CapitalizeDecorator:
      * Create a class that inherits from the base Decorator class.
      * Implement a method `correct_name` that capitalizes the output of `@nameable.correct_name`.
  - For the TrimmerDecorator:
      * Create a class that inherits from the base Decorator class.
      * Implement a method `correct_name` that makes sure that the output of `@nameable.correct_name` has a maximum of 10 characters. If it's longer it should trim the word.

Thanks

2023-02-08 17:02 UTC, rloterh requested changes
Hi Koami, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  🏃 

## Highlights 👍  
- Good job with pattern implementation so far!
- Professional ReadMe!

## Required Changes ♻️
_Kindly check the inline comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

_Kindly check the inline comments marked **[OPTIONAL]** under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 17:02 UTC, rloterh commented on decorators/decorator.rb
> +  def initialize(params)
- [ ] OPTIONAL
It's a best practice to mark `nameable` with `attr_accessor`, to give an indication that we intend to both _read_ and _write_ this variable. Let's endeavor to improve upon the same.

2023-02-08 17:02 UTC, rloterh commented on decorators/capitalizedecorator.rb
> +    @nameable.correct_name.upcase
- [ ] We actually want you to capitalize the first letter of the given name, therefore it will be appropriate to use `capitalize` method here. Let's improve upon this aspect.

**Output from your app:**
![image](https://user-images.githubusercontent.com/12745474/217599182-468eedc0-72c4-45b6-b102-5c48a46d6243.png)

2023-02-08 17:02 UTC, rloterh commented on decorators/decorator.rb
> +    super
- [ ] The `super` keyword used here appears redundant. Kindly remove it to enable your app run as intended.

2023-02-08 17:02 UTC, rloterh commented on entity/person.rb
> +    super
- [ ] The `super` keyword used here appears redundant. Kindly remove it to enable your app run as intended.

2023-02-08 17:02 UTC, rloterh commented on main.rb
> +capitalized_trimmed_person = TrimmerDecorator.new(capitalizedPerson)
- [ ] OPTIONAL
The argument used on `line 8` of your `main.rb` should be `capitalized_person` instead of `capitalizedPerson`, following the previous lines of your code.

2023-02-10 17:08 UTC, roshan-bajgain approved these changes
Hi @hopeforkoami, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 17:12 UTC, merged